### ISSUE TITLE
error for `npm run start` based on vite

### ISSUE THREAD

**Issue by rickythink** [qDanik/frontend-layered-architecture#17]
ERROR  11:31:49 [vite] Internal server error:                                                                                                                               11:31:49
  × Expression expected
    ╭─[/Users/ricky/project/3.play/43.react-architecture/src/core/adapters/i18next/i18next.adapter.ts:13:1]
 13 │ 
 14 │ import { I18N_CONFIG } from './i18next.constants';
 15 │ 
 16 │ @Injectable()

**Comment by qDanik** [comment]
@rickythink I've updated the vite plugin that's currently supporting decorators.
